In [87]:
import pickle
import pandas as pd
import re

In [2]:
df1 = pickle.load(open("all_linkedin_worldwide_datascience_jobs_with_salary.pkl", "rb"))
df2 = pickle.load(open("all_gd_company_infos.pkl", "rb"))

In [3]:
df2.describe()

,company,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
count,249,249,249,249,249,249,249,249,249,249
unique,173,104,9,71,57,24,27,55,55,22
top,Amazon Web Services (AWS),"San Francisco, CA (US)",10000+ employees,Company - Private,Computer Hardware & Software,$10+ billion (CAD) per year,3.9,77,-1,2.8
freq,6,37,94,92,31,61,38,19,31,35

In [4]:
df2 = df2.drop_duplicates(subset = 'company')

In [6]:
df2.describe()

,company,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
count,173,173,173,173,173,173,173,173,173,173
unique,173,103,9,71,57,24,27,55,55,22
top,Toyota Research Institute,"San Francisco, CA (US)",10000+ employees,Company - Private,Computer Hardware & Software,Unknown / Non-Applicable,3.9,100,-1,2.8
freq,1,20,55,71,15,44,21,14,25,23

In [7]:
jobs = df1.merge(df2, how = 'left', on = 'company')

In [8]:
jobs

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
0,TikTok,Data Scientist - TikTok Ads,"Mountain View, CA",https://www.linkedin.com/jobs/view/2148228403/...,"$144,000/yr",TikTok is the leading destination for short-fo...,[],,-1,-1,-1,-1,-1,-1,-1,-1,2.7
1,Tesla,Data Scientist,"Fremont, CA",https://www.linkedin.com/jobs/view/2147874276/...,"$107,000/yr",THE ROLE\n\nTesla's mission is to accelerate t...,[ Contribute on all the stages of Data Science...,Seniority Level\nEntry level\nIndustry\nAutomo...,"Palo Alto, CA (US)",10000+ employees,Company - Public (TSLA),Transportation Equipment Manufacturing,$2 to $5 billion (CAD) per year,3.5,59,75,2.9
2,Facebook,"Data Scientist, Finance","Menlo Park, CA",https://www.linkedin.com/jobs/view/2016420647/...,"$150,000/yr",Facebook's mission is to give people the power...,[Apply your expertise in quantitative analysis...,Industry\nInternet\nEmployment Type\nFull-time...,"Menlo Park, CA (US)",10000+ employees,Company - Public (FB),Internet,$5 to $10 billion (CAD) per year,4.4,90,94,3.1
3,The New York Times,Data Scientist,"New York, NY",https://www.linkedin.com/jobs/view/1988976314/...,"$130,000/yr",Job Description\n\nThe New York Times is commi...,[ Reframe newsroom and business objectives as ...,Seniority Level\nMid-Senior level\nIndustry\nO...,"New York, NY (US)",1001 to 5000 employees,Company - Public (NYT),News Outlets,$1 to $2 billion (CAD) per year,3.8,80,95,2.9
4,Cerebri AI,Data Scientist,"Toronto, ON",https://www.linkedin.com/jobs/view/1984995996/...,"CA$88,300/yr",About Cerebri AI Cerebri AI CVX platform uses ...,[Experience working with and creating data arc...,Seniority Level\nEntry level\nIndustry\nInform...,"Austin, TX (US)",1 to 50 employees,Company - Private,Enterprise Software & Network Solutions,Unknown / Non-Applicable,3.9,75,80,2.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,Apple,Data Scientist - Strategic Data Solutions,"Austin, TX",https://www.linkedin.com/jobs/view/1991635599/...,"$115,000/yr",Summary\n\nImagine what you could do here. At ...,[],Industry\nConsumer Electronics\nEmployment Typ...,"Cupertino, CA (US)",10000+ employees,Company - Public (AAPL),Computer Hardware & Software,$10+ billion (CAD) per year,4.2,83,93,3
255,Facebook,Research Data Scientist,"Bellevue, WA",https://www.linkedin.com/jobs/view/2023622992/...,"$155,000/yr",Facebook's mission is to give people the power...,"[Build pragmatic, scalable, and statistically ...",Industry\nInternet\nEmployment Type\nFull-time...,"Menlo Park, CA (US)",10000+ employees,Company - Public (FB),Internet,$5 to $10 billion (CAD) per year,4.4,90,94,3.1
256,Amazon Web Services (AWS),Data Scientist,"Jersey City, NJ",https://www.linkedin.com/jobs/view/1991684708/...,"$134,000/yr",Description\n\nExcited by using massive amount...,[ Understand the customer’s business need and ...,Industry\nComputer Software Information Techno...,"Seattle, WA (US)",10000+ employees,Company - Public (AMZN),Internet,$10+ billion (CAD) per year,3.9,77,85,3
257,PlayStation,Data Scientist Intern,"San Mateo, CA",https://www.linkedin.com/jobs/view/2149521530/...,"$139,000/yr",PlayStation isn’t just the Best Place to Play ...,[Building models to predict customer behaviors...,Seniority Level\nInternship\nIndustry\nCompute...,"San Mateo, CA (US)",5001 to 10000 employees,1994,Subsidiary or Business Segment,Video Games,3.7,75,73,2.7
258,Lockheed Martin,Data Scientist,"Shelton, CT",https://www.linkedin.com/jobs/view/2014612647/...,"$112,000/yr",Description:Performs exploratory research and ...,[],Seniority Level\nEntry level\nIndustry\nConstr...,"Bethesda, MD (US)",10000+ employees,Company - Public (LMT),Aerospace & Defence,$10+ billion (CAD) per year,3.9,78,96,2.6

In [9]:
jobs.describe()

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
count,259,259,259,259,259,259,259,259,248,248,248,248,248,248,248,248,248
unique,181,80,136,243,131,204,175,109,103,9,71,57,24,27,55,55,22
top,Amazon Web Services (AWS),Data Scientist,"San Francisco, CA",https://www.linkedin.com/jobs/view/1991652913/...,$\n/yr,Description\n\nWhat is the most relevant busin...,[],-1,"San Francisco, CA (US)",10000+ employees,Company - Private,Computer Hardware & Software,$10+ billion (CAD) per year,3.9,77,-1,2.8
freq,6,153,15,2,14,5,37,20,37,94,92,31,59,38,19,33,34

In [10]:
jobs = jobs.drop_duplicates(subset = 'href')

In [11]:
jobs.describe()

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
count,243,243,243,243,243,243,243,243,233,233,233,233,233,233,233,233,233
unique,181,80,136,243,131,204,175,109,103,9,71,57,24,27,55,55,22
top,Amazon Web Services (AWS),Data Scientist,"San Francisco, CA",https://www.linkedin.com/jobs/view/1971242283/...,$\n/yr,Description\n\nWhat is the most relevant busin...,[],-1,"San Francisco, CA (US)",10000+ employees,Company - Private,Computer Hardware & Software,$10+ billion (CAD) per year,3.9,77,-1,2.8
freq,5,140,15,1,14,4,36,19,34,90,88,29,56,35,17,30,34

In [18]:
pd.set_option('display.max_colwidth', -1)
jobs[jobs['salary'] == "$\n/yr"]['href']

86     https://www.linkedin.com/jobs/view/1942484976/?eBP=NotAvailableFromMidTier&recommendedFlavor=SCHOOL_RECRUIT&refId=d8dbfc26-b83b-46ef-abfb-7f25c4bcd308&trk=flagship3_search_srp_jobs
87     https://www.linkedin.com/jobs/view/2160505329/?eBP=NotAvailableFromMidTier&refId=d8dbfc26-b83b-46ef-abfb-7f25c4bcd308&trk=flagship3_search_srp_jobs
88     https://www.linkedin.com/jobs/view/2023755677/?eBP=JOB_SEARCH_ORGANIC&recommendedFlavor=SCHOOL_RECRUIT&refId=d8dbfc26-b83b-46ef-abfb-7f25c4bcd308&trk=flagship3_search_srp_jobs
89     https://www.linkedin.com/jobs/view/2161977357/?eBP=NotAvailableFromMidTier&recommendedFlavor=SCHOOL_RECRUIT&refId=d8dbfc26-b83b-46ef-abfb-7f25c4bcd308&trk=flagship3_search_srp_jobs
90     https://www.linkedin.com/jobs/view/513112591/?eBP=JOB_SEARCH_ORGANIC&recommendedFlavor=JOB_SEEKER_QUALIFIED&refId=4043f370-ec35-4976-8726-3f3405643807&trk=flagship3_search_srp_jobs
91     https://www.linkedin.com/jobs/view/2011108874/?eBP=NotAvailableFromMidTier&recommendedFlavor=SCHOOL_RECRUIT&refId=4043f370-ec35-4976-8726-3f3405643807&trk=flagship3_search_srp_jobs
93     https://www.linkedin.com/jobs/view/2158938031/?eBP=NotAvailableFromMidTier&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=4043f370-ec35-4976-8726-3f3405643807&trk=flagship3_search_srp_jobs
146    https://www.linkedin.com/jobs/view/2023672975/?eBP=CwEAAAF0nbU7Ggc8ACwG51PFgztPooObyxvrEZwRxkodiNdSXFSqrC861USlwFdNH9vybHV-npRgY9z8c_KGOj7q8vxVLvgIsqalq4YfnVdgxIcakaAwmB3HrSb7DLerJ1h-B_SYRcEBO8YxBpURyOaNC2VJfzqhn5Z1tGELvQl-soFsObl8_cYCEaVAvRLvbIZMOhANj0u7t7lgf2FG17bxlbB2dbPSkgpUp-NV1XvDRBU1sb4aK84s16e-oChcbljVa7eDT1359TGGZPXKQ1cAeVo7qufl6OXhVSRKJe7zd9ftF1aQfk9iGIGbiyAJBMf1FUtLOlz4rJA8A2KgkFMi6RnjijdtNYu4g6Fw1r-I1ZedJmlqklDOg762vCC0zSs0BK04GrjDzjjue-R6&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=W0y1PI3E3QZ9Yy9wGgoDTQ%3D%3D&trk=flagship3_search_srp_jobs
147    https://www.linkedin.com/jobs/view/2014415963/?eBP=NotAvailableFromVoyagerAPI&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=BPSPc8qM4%2B0u%2BqXCT0KRxw%3D%3D&trk=flagship3_search_srp_jobs
148    https://www.linkedin.com/jobs/view/1974474609/?eBP=NotAvailableFromVoyagerAPI&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=EDyKpFXwFsMI1seMYFR36Q%3D%3D&trk=flagship3_search_srp_jobs
149    https://www.linkedin.com/jobs/view/2021297929/?eBP=NotAvailableFromVoyagerAPI&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=pIdylqS%2Fb0zqhXLRv803qA%3D%3D&trk=flagship3_search_srp_jobs
150    https://www.linkedin.com/jobs/view/2163962861/?eBP=NotAvailableFromVoyagerAPI&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=0KMGdQRoZ89RRlIBcSKTug%3D%3D&trk=flagship3_search_srp_jobs
151    https://www.linkedin.com/jobs/view/2004310389/?eBP=CwEAAAF0nbU7Gybg4g9GvPUMCmQ741JKD_LrrUHr9i_oxzuqukFW5XSRJ87Ql-Y-506QhdAcOhanXRTPEdpxx5v7J0PnFraff00tBCpZmOup53fyYWESc6TR42_hKzOzlT49M5t7YniMkqJinV-Jb81Jt4Un7l_JqXbYOOJ0oQvRL9rYp56dguS9RJc9XE9GMquvivJ-IqbD9sUJujz9MVhBRX68_VZKzRPMcgQVoWXlfDPeCZY7RgA8Am0sfIhnvvBd9Xz9YRW_D8ANWyUlj29y4lkq761lPZjMDKzVZhwO03p73uM7D0CoYArcpieYLMzfVdyBHIRslwHjG-7ZSFwCy6Ib2Pttejp2rz2pbXY4siBWpSWMRBjnNut0aCAl-I5Y4LsWAf3zIet2dLOW&recommendedFlavor=SCHOOL_RECRUIT&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=LGulas9Dm%2BFVtznlEivfPw%3D%3D&trk=flagship3_search_srp_jobs
152    https://www.linkedin.com/jobs/view/2007984424/?eBP=NotAvailableFromVoyagerAPI&refId=35e38fd6-c650-47de-a0be-16ecf21421d0&trackingId=rBaYjxHyLJiFPm9noQmVoQ%3D%3D&trk=flagship3_search_srp_jobs
Name: href, dtype: object

In [19]:
jobs = jobs.drop(index = [91,93])

In [29]:
jobs = jobs.reset_index(drop=True)

In [35]:
indices = jobs[jobs['salary'] == "$\n/yr"].index
missing_salaries = {86: 117000, 87: 79500, 88: 126000, 89: 118000, 90: 107000, 128: 140000, 129: 94000, 130: 11700, 131: 106000, 132: 108500, 133: 73067, 134: 94000}
for index in indices:
    jobs.iloc[index]['salary'] = missing_salaries[index]

In [39]:
jobs['salary'].unique()

array(['$144,000/yr', '$107,000/yr', '$150,000/yr', '$130,000/yr',
       'CA$88,300/yr', '$102,000/yr', '$116,000/yr', 'CA$84,800/yr',
       'CA$88,000/yr', '$85,000/yr', '$125,000/yr', '$97,000/yr',
       '$157,000/yr', '$153,000/yr', '$146,000/yr', '$133,000/yr',
       '£45,400/yr', '$120,000/yr', '$122,000/yr', '$94,700/yr',
       '$148,000/yr', 'CA$73,027/yr – CA$84,510/yr', '$121,000/yr',
       '$91,100/yr', '$155,000/yr', '$91,400/yr', '$131,000/yr',
       'CA$103,000/yr', '$117,000/yr', '$112,000/yr', '$126,000/yr',
       '$111,000/yr', '$136,000/yr', '$75,200/yr', '$85,900/yr',
       '$91,900/yr', '$106,000/yr', '$123,000/yr', '$93,400/yr',
       '£43,100/yr', '$135,000/yr', '$57,300/yr', '$127,000/yr',
       '£40,000/yr – £45,000/yr', '$128,000/yr', '$101,000/yr',
       '$113,000/yr', '$95,700/yr', '$94,900/yr', '$205,000/yr',
       '$151,000/yr', '$75,400/yr', 'CA$87,400/yr',
       '€30,000/yr – €45,000/yr', '£49,200/yr',
       '$120,000/yr – $133,000/yr', '$105,000/yr', '$172,000/yr',
       '$139,000/yr', '$96,600/yr', 'CA$89,000/yr',
       '$56,600/yr – $60,000/yr', 117000, 79500, 126000, 118000, 107000,
       '£60,000/yr – £100,000/yr', '$95,900/yr', '$80,100/yr',
       '$102,000/yr – $145,000/yr', 'CA$108,000/yr', 'CA$92,900/yr',
       '$94,100/yr', '£40,000/yr – £58,000/yr', '£65,000/yr – £80,000/yr',
       '$132,000/yr', '$94,600/yr', '$100,000/yr – $130,000/yr',
       '$109,000/yr', '$87,200/yr', '$88,500/yr', '$129,000/yr',
       '$72,900/yr', '$96,500/yr', '$120,000/yr – $140,000/yr',
       '$70/hr – $100/hr', '$95,000/yr', 140000, 94000, 11700, 106000,
       108500, 97800, '£56,900/yr', '$88,000/yr', '$99,200/yr',
       '$137,000/yr', '$79,100/yr', '$93,300/yr', '$86,400/yr',
       '$95,600/yr', '$92,600/yr', '$99,800/yr', '$97,200/yr',
       '$93,500/yr', '$95,300/yr', '$93,000/yr', '$94,400/yr',
       '$162,000/yr', '$93,700/yr', '$147,000/yr', 'CA$91,600/yr',
       '$118,000/yr', '$94,800/yr', '$94,200/yr', '$88,700/yr',
       '$82,100/yr', '$96,700/yr', '$158,000/yr', '$87,700/yr',
       '$108,000/yr', '$91,600/yr', '$168,000/yr', '$74,500/yr',
       '$115,000/yr', '$114,000/yr', '$84,900/yr', '$91,800/yr',
       '$134,000/yr', '$95,200/yr', '$140,000/yr', '$142,000/yr',
       '$170,000/yr', '$91,000/yr', '£35,310/yr – £50,938/yr',
       '£50,000/yr – £70,000/yr', '$90,000/yr – $120,000/yr',
       '£65,000/yr – £70,000/yr', '$92,500/yr', '$87,900/yr'],
      dtype=object)

In [40]:
jobs[jobs['salary'] == 'CA$73,027/yr – CA$84,510/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
24,Statistics Canada,Data Scientist,"Ottawa, ON",https://www.linkedin.com/jobs/view/2004852309/?eBP=NotAvailableFromVoyagerAPI&recommendedFlavor=ACTIVELY_HIRING_COMPANY&refId=ddbc81ec-aaff-4a31-b62c-eecf8d0db0c3&trk=flagship3_search_srp_jobs,"CA$73,027/yr – CA$84,510/yr","Work Environment:\n\nAre you interested in working with millions of records transactional data, satellite images, news articles? Would you like to have the chance to work on a project that could have a direct impact on some of the major economic and social indicators for the country? Do you have an interest in Natural Language Processing, Web information retrieval, image classification, data anomalies detection? Are you interested in modeling technics, neural networks, and cloud infrastructure for high processing capacity?","[Become familiar with the business case and the feasibility and implementation challenges related to homomorphic encryption, including designing compute models, encoding strategies, security parameters, validation and optimization., Become familiar with issues related to secure multi-party computation, with federated and distributed machine learning models., Programming in Python and C++ to implement homomorphic encryption schemes, secure multi-party computation protocols and distributed machine learning algorithms., Produce relevant results by using various visualization tools., Participate in the writing of a technical report summarizing the steps and the results. The report will also provide recommendations., Present the main results of the project to all the internal and external stakeholders and partners., Master's degree from a recognized post-secondary institution with specialization in Statistics, Mathematics, Physics, Computer Science or other related areas., Experience with machine learning algorithms, in particular natural language processing, data wrangling, pre and post-processing and visualization., Experience with deep learning libraries and emerging platforms and tools, including Docker technology., A strong foundation in algebraic number theory and ring theory, especially as it pertains to lattice-based cryptography and homomorphic encryption., Familiarity with public and private key cryptographic schemes, as well as secret sharing protocols., Proficient in Python and C++ and familiarity with homomorphic encryption libraries, including Microsoft SEAL., Se familiariser avec le cas à l’étude et les défis de faisabilité et de mise en œuvre liés au chiffrement homomorphe, notamment la conception de modèles de calcul, les stratégies de codage, les paramètres de sécurité, la validation et l'optimisation., Se familiariser avec les questions liées au calcul multipartite sécurisé, avec les modèles d'apprentissage automatique centraux et distribués., Programmation en Python et C++ pour mettre en œuvre des schémas de chiffrement homomorphe, des protocoles de calcul multipartite sécurisé et des algorithmes d'apprentissage automatique distribués., Produire des résultats pertinents en utilisant divers outils de visualisation., Participer à la rédaction d'un rapport technique résumant les étapes et les résultats. Ce rapport contiendra également des recommandations., Présenter les principaux résultats du projet à tous les intervenants et partenaires internes et externes., Maîtrise d'un établissement postsecondaire reconnu avec spécialisation dans des domaines tels que les mathématiques, la physique, l'informatique et d'autres domaines connexes.&nbsp;, Expérience des algorithmes d'apprentissage automatique, en particulier le traitement du langage naturel, la manipulation de données (<i>data wrangling</i>), la préparation et le post-traitement ainsi que la visualisation. , Expérience avec les bibliothèques d'apprentissage profond et aux plateformes et outils émergents, notamment la technologie Docker., Une solide base en théorie algébrique des nombres et en théorie des anneaux, en particulier en ce qui concerne la cryptographie basée sur les réseaux euclidiens et le cryptage homomorphe., Une connaissance des schémas cryptographiques à clés publiques et secrètes, ainsi que des protocoles de partage de secrets., Maîtrise de Python et de C++ et familiarité avec les bibliothèques de cryptage homomorphe, y compris Microsoft SEAL.]",,"Ottawa, ON",Unknown,Government,Government Agencies,Unknown / Non-Applicable per year,3.8,76,86,2.8

In [52]:
jobs.iloc[24]['salary'] = 58849

In [53]:
jobs[jobs['salary'] == '£40,000/yr – £45,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
52,Edrington,Data Scientist,"Glasgow, Scotland, United Kingdom",https://www.linkedin.com/jobs/view/2011661352/...,"£40,000/yr – £45,000/yr",Edrington is headquartered in Scotland and emp...,[Lead the consumer data science approach withi...,-1,"Glasgow, Scotland (UK)",1001 to 5000 employees,Company - Private,Food & Drink Manufacturing,$500 million to $1 billion (CAD) per year,3.8,64,95,2.1

In [54]:
jobs.iloc[52]['salary'] = 54000

In [55]:
jobs[jobs['salary'] == '€30,000/yr – €45,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
71,dunnhumby,Data Scientist,"Dublin, Ireland",https://www.linkedin.com/jobs/view/2023948856/...,"€30,000/yr – €45,000/yr",Applied Data Scientist\n\ndunnhumby is looking...,[Using cutting-edge data science and machine l...,,"Hammersmith, England (UK)",1001 to 5000 employees,Company - Private,Consulting,$500 million to $1 billion (CAD) per year,4.0,82,94,3

In [56]:
jobs.iloc[71]['salary'] = 44000

In [57]:
jobs[jobs['salary'] == '$120,000/yr – $133,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
76,Berkeley Lab,Genomics Data Scientist,"Berkeley, CA",https://www.linkedin.com/jobs/view/1983048753/...,"$120,000/yr – $133,000/yr",Lawrence Berkeley National Lab’s (LBNL) Joint ...,"[<p>Take a lead role in developing, debugging ...",,"Berkeley, CA (US)",5001 to 10000 employees,Government,Regional & County Councils,$100 to $500 million (CAD) per year,4.1,81,91,2.7

In [58]:
jobs.iloc[76]['salary'] = 126500

In [59]:
jobs[jobs['salary'] == '$56,600/yr – $60,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
85,Arizona State University,Data Scientist,"Phoenix, Arizona, United States",https://www.linkedin.com/jobs/view/2000022726/...,"$56,600/yr – $60,000/yr",Data Scientist\nArizona State University\nCamp...,[],Job Details\nIndustry\nHigher Education\nEmplo...,-1,-1,-1,-1,-1,-1,-1,-1,2.4
183,Arizona State University,Data Scientist,"Phoenix, Arizona, United States",https://www.linkedin.com/jobs/view/2000022726/...,"$56,600/yr – $60,000/yr",Data Scientist\nArizona State University\nCamp...,[],,-1,-1,-1,-1,-1,-1,-1,-1,2.4

In [60]:
jobs.iloc[85]['salary'] = 58300
jobs.iloc[183]['salary'] = 58300

In [61]:
jobs[jobs['salary'] == '£60,000/yr – £100,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
91,&facts,Data Scientist,United Kingdom\nRemote,https://www.linkedin.com/jobs/view/2023714208/...,"£60,000/yr – £100,000/yr","What we're looking for...\nAt &facts, you'll b...",[A passion for helping small businesses thrive...,Job Details\nSeniority Level\nEntry level\nInd...,"Clute, TX (US)",51 to 200 employees,Company - Public,Unknown,Unknown / Non-Applicable per year,2.2,18,-1,1

In [62]:
jobs.iloc[91]['salary'] = 102000

In [63]:
jobs[jobs['salary'] == '$102,000/yr – $145,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
94,Limetree,Data Scientist,Dallas-Fort Worth Metroplex,https://www.linkedin.com/jobs/view/1996346931/...,"$102,000/yr – $145,000/yr",Limetree is a behavioral marketing company wit...,[Understand member or customer churn and help ...,-1,"Sarasota, FL (US)",1 to 50 employees,Company - Private,Hotel & Resorts,Less than $1 million (CAD) per year,3.0,-1,-1,-1

In [64]:
jobs.iloc[94]['salary'] = 124000

In [65]:
jobs[jobs['salary'] == '£40,000/yr – £58,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
103,Full Circle Recruitment Ltd,Data Scientist,"London, England, United Kingdom",https://www.linkedin.com/jobs/view/2010225259/...,"£40,000/yr – £58,000/yr",R/Python - Data Scientist £40-58K + Package\n\...,[],Job Details\nSeniority Level\nMid-Senior level...,1 to 50 employees,Unknown,Staffing & Outsourcing,Less than $1 million (CAD) per year,-1,3.8,82,-1,3.6
139,Full Circle Recruitment Ltd,Data Scientist,"London, England, United Kingdom",https://www.linkedin.com/jobs/view/2010225259/...,"£40,000/yr – £58,000/yr",R/Python - Data Scientist £40-58K + Package\n\...,[],,1 to 50 employees,Unknown,Staffing & Outsourcing,Less than $1 million (CAD) per year,-1,3.8,82,-1,3.6

In [66]:
jobs.iloc[103]['salary'] = 62000
jobs.iloc[139]['salary'] = 62000

In [67]:
jobs[jobs['salary'] == '£65,000/yr – £80,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
104,Client Server,Data Scientist,"London, GB",https://www.linkedin.com/jobs/view/2013834919/...,"£65,000/yr – £80,000/yr",Data Scientist London to £80k\n\nData Scientis...,"[Strong record of academic achievement, 2.1 or...",-1,"London, England (UK)",51 to 200 employees,Company - Private,Staffing & Outsourcing,Unknown / Non-Applicable,4.5,92,100,3.1

In [68]:
jobs.iloc[104]['salary'] = 92383

In [69]:
jobs[jobs['salary'] == '$100,000/yr – $130,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
109,Parker and Lynch,Data Scientist,"Orange County, California, United States",https://www.linkedin.com/jobs/view/2023648973/...,"$100,000/yr – $130,000/yr",**PLEASE READ FULL JOB QUALIFICATIONS BEFORE Y...,"[Design Data Acquisition Strategy , Define Key...",Job Details\nSeniority Level\nMid-Senior level...,"Jacksonville, FL (US)",501 to 1000 employees,Company - Public,Staffing & Outsourcing,Unknown / Non-Applicable,3.9,86,68,2.4

In [70]:
jobs.iloc[109]['salary'] = 115000

In [71]:
jobs[jobs['salary'] =='$120,000/yr – $140,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
122,Codex Recruitment - Data Analytics and EPM Rec...,Data Scientist,San Francisco Bay Area,https://www.linkedin.com/jobs/view/2013720049/...,"$120,000/yr – $140,000/yr","Data Scientist – San Francisco - $120-140,000\...",[],Job Details\nSeniority Level\nMid-Senior level...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
jobs.iloc[122]['salary'] = 130000

In [73]:
jobs[jobs['salary'] == '$70/hr – $100/hr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
125,Big Cloud,Data Scientist,"60606, Chicago, Illinois, United States",https://www.linkedin.com/jobs/view/2023937180/...,$70/hr – $100/hr,Are you a Data Scientist with at least 5 years...,[A minimum of a masters degree in computer sci...,-1,"Manchester, England (UK)",1 to 50 employees,Company - Private,Staffing & Outsourcing,Unknown / Non-Applicable,5.0,100,100,3.5
212,Big Cloud,Data Scientist,"Chicago, IL",https://www.linkedin.com/jobs/view/2023937180/...,$70/hr – $100/hr,Are you a Data Scientist with at least 5 years...,[A minimum of a masters degree in computer sci...,-1,"Manchester, England (UK)",1 to 50 employees,Company - Private,Staffing & Outsourcing,Unknown / Non-Applicable,5.0,100,100,3.5

In [74]:
jobs.iloc[125]['salary'] = 153000
jobs.iloc[212]['salary'] = 153000

In [75]:
jobs[jobs['salary'] =='£35,310/yr – £50,938/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
219,DWP Digital,Data Scientist,"Leeds, England, United Kingdom",https://www.linkedin.com/jobs/view/2011648281/...,"£35,310/yr – £50,938/yr","Data Scientist: Up to £50,938, 27% pension con...",[<strong>Are you a problem solver who is creat...,-1,"London, England (UK)",10000+ employees,Government,Government Agencies,Unknown / Non-Applicable,3.8,73,81,3.1

In [76]:
jobs.iloc[219]['salary'] = 54967

In [77]:
jobs[jobs['salary'] == '£50,000/yr – £70,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
220,MBN Solutions,Data Scientist,"London, England Metropolitan Area",https://www.linkedin.com/jobs/view/2011658600/...,"£50,000/yr – £70,000/yr","MBNs client, an award-winning Telecommunicatio...","[Experience in end to end model development, i...",-1,"Glasgow, Scotland (UK)",1 to 50 employees,Company - Private,Unknown,Unknown / Non-Applicable per year,3.8,66,-1,3

In [78]:
jobs.iloc[220]['salary'] = 76455

In [79]:
jobs[jobs['salary'] ==  '$90,000/yr – $120,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
221,Robert Half,Data Scientist,"Troy, MI",https://www.linkedin.com/jobs/view/2163117236/...,"$90,000/yr – $120,000/yr",Description\n\nThis is your chance to make an ...,[],Seniority Level\nEntry level\nIndustry\nInform...,"Menlo Park, CA (US)",10000+ employees,Company - Public (RHI),Staffing & Outsourcing,$2 to $5 billion (CAD) per year,3.5,63,68,2.3

In [80]:
jobs.iloc[221]['salary'] = 105000

In [81]:
jobs[jobs['salary'] == '£65,000/yr – £70,000/yr']

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
222,Apply Recruitment,Data Scientist,"Cheshire, England, United Kingdom\nRemote",https://www.linkedin.com/jobs/view/2006329197/...,"£65,000/yr – £70,000/yr","Data Scientist required, working in the R&D te...",[Statistical analysis experience across a rang...,-1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [82]:
jobs.iloc[222]['salary'] = 86012

In [90]:
def convert_salary_to_usd(salary):

    conversion_rate = {'CA' : 0.75, '€' : 1.16, '£' : 1.27}
    
    if type(salary) == int:
        return salary

    elif 'CA' in salary:
        salary = int(re.sub('[^0-9]','', salary))
        salary = salary * conversion_rate['CA']
        salary = round(salary)
        return salary
    
    elif '€' in salary:
        salary = int(re.sub('[^0-9]','', salary))
        salary = salary * conversion_rate['€']
        salary = round(salary)
        return salary
    
    elif '£' in salary:
        salary = int(re.sub('[^0-9]','', salary))
        salary = salary * conversion_rate['£']
        salary = round(salary)
        return salary

    else:
        salary = int(re.sub('[^0-9]','', salary))
        return salary

In [97]:
jobs['salary'] = jobs['salary'].apply(convert_salary_to_usd)

In [114]:
jobs['href'] = jobs['href'].str[0:45]

In [115]:
jobs = jobs.drop_duplicates('href')

In [118]:
jobs = jobs.reset_index(drop=True)

In [119]:
jobs

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
0,TikTok,Data Scientist - TikTok Ads,"Mountain View, CA",https://www.linkedin.com/jobs/view/2148228403,144000,TikTok is the leading destination for short-fo...,[],,-1,-1,-1,-1,-1,-1,-1,-1,2.7
1,Tesla,Data Scientist,"Fremont, CA",https://www.linkedin.com/jobs/view/2147874276,107000,THE ROLE\n\nTesla's mission is to accelerate t...,[ Contribute on all the stages of Data Science...,Seniority Level\nEntry level\nIndustry\nAutomo...,"Palo Alto, CA (US)",10000+ employees,Company - Public (TSLA),Transportation Equipment Manufacturing,$2 to $5 billion (CAD) per year,3.5,59,75,2.9
2,Facebook,"Data Scientist, Finance","Menlo Park, CA",https://www.linkedin.com/jobs/view/2016420647,150000,Facebook's mission is to give people the power...,[Apply your expertise in quantitative analysis...,Industry\nInternet\nEmployment Type\nFull-time...,"Menlo Park, CA (US)",10000+ employees,Company - Public (FB),Internet,$5 to $10 billion (CAD) per year,4.4,90,94,3.1
3,The New York Times,Data Scientist,"New York, NY",https://www.linkedin.com/jobs/view/1988976314,130000,Job Description\n\nThe New York Times is commi...,[ Reframe newsroom and business objectives as ...,Seniority Level\nMid-Senior level\nIndustry\nO...,"New York, NY (US)",1001 to 5000 employees,Company - Public (NYT),News Outlets,$1 to $2 billion (CAD) per year,3.8,80,95,2.9
4,Cerebri AI,Data Scientist,"Toronto, ON",https://www.linkedin.com/jobs/view/1984995996,66225,About Cerebri AI Cerebri AI CVX platform uses ...,[Experience working with and creating data arc...,Seniority Level\nEntry level\nIndustry\nInform...,"Austin, TX (US)",1 to 50 employees,Company - Private,Enterprise Software & Network Solutions,Unknown / Non-Applicable,3.9,75,80,2.4
5,"Anthem, Inc.",Data Scientist,"Atlanta, GA",https://www.linkedin.com/jobs/view/2164180804,102000,Description\n\nSHIFT: Day Job\n\nSCHEDULE: Ful...,"[Statistical Analysis, Scripted Analytics, Pre...",Seniority Level\nEntry level\nIndustry\nInsura...,"Indianapolis, IN (US)",10000+ employees,Company - Public (ANTM),Insurance Operators,$10+ billion (CAD) per year,3.4,63,66,2.7
6,"University of California, San Francisco",Research Data Scientist,"San Francisco, CA",https://www.linkedin.com/jobs/view/1942484976,116000,Job Overview\n\nJob Summary\n\nThe Research Da...,[ BA/BS degree with a major in a related field...,Industry\nHigher Education\nEmployment Type\nF...,"San Francisco, CA (US)",10000+ employees,College / University,Unknown,$50 to $100 million (CAD) per year,4.2,82,89,2.8
7,Loblaw Companies Limited,Data Scientist,"Brampton, ON",https://www.linkedin.com/jobs/view/2148179265,63600,"Location:\n1 Presidents Choice Circle, Brampto...","[Build statistical, descriptive and predictive...",Seniority Level\nEntry level\nIndustry\nInform...,"Brampton, ON",10000+ employees,Company - Public (L),Vehicle Dealers,$10+ billion (CAD) per year,3.5,69,80,2.2
8,The University of British Columbia,Junior Data Scientist,"West Point Grey, BC",https://www.linkedin.com/jobs/view/2008144962,66000,Job Summary\n\nThe UBC Data Science Institute ...,"[ Design, develop, implement and evaluate meth...",Seniority Level\nEntry level\nIndustry\nNon-pr...,"Vancouver, BC",10000+ employees,College / University,Colleges & Universities,$2 to $5 billion (CAD) per year,4.2,87,82,2.7
9,Booz Allen Hamilton,Data Scientist,"Herndon, VA",https://www.linkedin.com/jobs/view/2150469221,85000,Job Number: R0091474\n\nData Scientist\n\nThe ...,"[1+ years of experience with machine learning,...",Seniority Level\nEntry level\nIndustry\nInform...,"McLean, VA (US)",10000+ employees,Company - Public (BAH),Consulting,$5 to $10 billion (CAD) per year,3.9,76,93,2.7
10,PicnicHealth,Data Scientist / Biostatistician,"San Francisco, CA",https://www.linkedin.com/jobs/view/2023894563,144000,Overview\n\nPicnicHealth is all about making m...,"[Use PicnicHealth’s large, multi-disease multi...",,"San Francisco, CA (US)",1 to 50 employees,Company - Private,Computer Hardware & Software,Unknown / Non-Applicable,4.8,100,-1,3
11,Johnson & Johnson,"Principal Data Scientist, Data Sciences","Titusville, NJ",https://www.linkedin.com/jobs/view/2011683327,125000,"Job Description\n\nJanssen Pharmaceuticals, In...","[Ph.D. with 5 years of industry experience, or...",Industry\nHospital & Health Care Medical Devic...,"New Brunswick, NJ (US)",10000+ employees,Company - Public (JNJ),Biotech & Pharmaceuticals,$10+ billion (CAD) per year,4.1,83,95,2.9
12,Ford Motor Company,Data Scientist,"Dearborn, MI",https://www.linkedin.com/jobs/view/2163903973,97000,Job Description\n\nData Scientist positions of...,[Requires master's or foreign equivalent degre...,Seniority Level\nEntry level\nIndustry\nAutomo...,"Dearborn, MI (US)",10000+ employees,Company - Public (F),Transportation Equipment Manufacturing,$10+ billion (CAD) per year,4.0,80,67,2.8
13,Stripe,"Data Scientist, Radar","Seattle, WA",https://www.linkedin.com/jobs/view/1983860797,157000,We’re looking for data scientists to join the ...,[Work closely with product and business teams ...,-1,"San Francisco, CA (US)",1001 to 5000 employees,Company - Private,Internet,Unknown / Non-Applicable,4.1,83,92,3
14,Amazon Web Services (AWS),Data Scientist,"Seattle, WA",https://www.linkedin.com/jobs/view/1991652913,116000,Description\n\nWhat is the most relevant busin...,"[ Research, develop and build classification a...",Industry\nComputer Software Information Techno...,"Seattle, WA (US)",10000+ employees,Company - Public (AMZN),Internet,$10+ billion (CAD) per year,3.9,77,85,3
15,Square,"Data Scientist, Risk","San Francisco, CA",https://www.linkedin.com/jobs/view/1995037157,153000,Company Description\n\nSquare builds common bu...,"[Diagnose problems and develop compelling, dat...",Seniority Level\nAssociate\nIndustry\nComputer...,"San Francisco, CA (US)",1001 to 5000 employees,Company - Public (SQ),Computer Hardware & Software,$1 to $2 billion (CAD) per year,4.0,81,87,3
16,Bayer,Biotech Data Scientist,"Berkeley, CA",https://www.linkedin.com/jobs/view/1995091624,146000,Your Tasks And Responsibilities\n\nThe primary...,[Work with partners across the Biotech organiz...,Seniority Level\nEntry level\nIndustry\nChemic...,"São Paulo, São Paulo (Brazil)",5001 to 10000 employees,Company - Private,Biotech & Pharmaceuticals,$10+ billion (CAD) per year,4.1,84,72,3
17,Lyft,"Data Scientist, Decisions","New York, NY",https://www.linkedin.com/jobs/view/1991640309,133000,"At Lyft, our mission is to improve people’s li...",[Leverage data and analytic frameworks to iden...,Seniority Level\nMid-Senior level\nIndustry\nI...,"San Francisco, CA (US)",5001 to 10000 employees,Company - Public (LYFT),Computer Hardware & Software,Unknown / Non-Applicable,3.8,68,77,2.8
18,MATCHESFASHION,Data Scientist,"London, England, United Kingdom",https://www.linkedin.com/jobs/view/2149281425,57658,At MATCHESFASHION we are on a mission to offer...,[We believe<strong> we all have a part to play...,Seniority Level\nMid-Senior level\nIndustry\nI...,"London, England (UK)",501 to 1000 employees,1987,Company - Private,"Department, Clothing, & Shoe Shops",2.9,44,67,2.5
19,Grammarly,Data Scientist,"San Francisco, CA",https://www.linkedin.com/jobs/view/1995003228,144000,The opportunity\nGrammarly empowers people to ...,"[ Within your first month, you will start deve...",Seniority Level\nEntry level\nIndustry\nInform...,"San Francisco, CA (US)",201 to 500 employees,Company - Private,Internet,Unknown / Non-Applicable,5.0,99,99,2.8
20,JetBlue Airways,Data Scientist,"New York, New York, United States",https://www.linkedin.com/jobs/view/2023647760,120000,Data Scientist\n\nPosition Summary\n\nThe Data...,[Collaborate with teams across the business to...,Seniority Level\nEntry level\nIndustry\nAirlin...,"Long Island City, NY (US)",10000+ employees,Company - Public (JBLU),Transportation Management,$5 to $10 billion (CAD) per year,4.0,78,82,2.8
21,Amazon,Data Scientist,"Seattle, WA",https://www.linkedin.com/jobs/view/2004877102,122000,Description\n\nAre you driven to leverage your...,[ Amazon offers competitive packages including...,Industry\nComputer Software Information Techno...,"Seattle, WA (US)",10000+ employees,Company - Public (AMZN),Internet,$10+ billion (CAD) per year,3.9,77,85,3
22,Tata Group,Data Scientist,"Atlanta, GA",https://www.linkedin.com/jobs/view/2162237772,94700,Researchand develop statistical learning model...,[Researchand develop statistical learning mode...,Seniority Level\nEntry level\nIndustry\nInform...,Mumbai (India),Unknown,Company - Private,Architectural & Engineering Services,$10+ billion (CAD) per year,3.7,78,98,2.9
23,NetApp,Data Scientist,San Francisco Bay Area,https://www.linkedin.com/jobs/view/2004891508,148000,About the Position\nThis Cloud Business Operat...,[Analyze usage and billing data from multiple ...,,"Sunnyvale, CA (US)",10000+ employees,Company - Public (NTAP),Enterprise Software & Network Solutions,$5 to $10 billion (CAD) per year,4.9,87,100,3
24,Statistics Canada,Data Scientist,"Ottawa, ON",https://www.linkedin.com/jobs/view/2004852309,58849,Work Environment:\n\nAre you interested in wor...,[Become familiar with the business case and th...,,"Ottawa, ON",Unknown,Government,Government Agencies,Unknown / Non-Applicable per year,3.8,76,86,2.8
25,Disney Streaming Services,Data Engineer (Marketing Data Eng Team),"New York, NY",https://www.linkedin.com/jobs/view/2163944327,121000,Job Summary\n\nThe Marketing Data Engineering ...,[Build and deploy streaming and batch data pip...,Seniority Level\nMid-Senior level\nIndustry\nI...,"New York, NY (US)",501 to 1000 employees,Company - Private,Internet,Unknown / Non-Applicable,3.7,64,83,2.5
26,Walmart,"Data Scientist, Technology","Bentonville, AR",https://www.linkedin.com/jobs/view/2148159422,91100,Position Summary... What you'll do...\nApplied...,[Applied Business Acumen: Supports the develop...,Seniority Level\nEntry level\nIndustry\nRetail...,"Bentonville, AR (US)",1001 to 5000 employees,Company - Public (WMT),"Department, Clothing, & Shoe Shops",$10+ billion (CAD) per year,3.7,72,87,2.2
27,Kaiser Permanente,Data Scientist,"Oakland, CA",https://www.linkedin.com/jobs/view/2152878571,155000,Description\n\nPerforms advanced data design a...,"[Works with physicians, epidemiologists, stati...",Seniority Level\nEntry level\nIndustry\nFinanc...,"Oakland, CA (US)",10000+ employees,Non-profit Organisation,Healthcare Services & Hospitals,$10+ billion (CAD) per year,4.0,77,81,2.9
28,General Motors,Data Scientist,"Warren, MI",https://www.linkedin.com/jobs/view/2150552482,102000,About GM\n\nThere’s never been a more exciting...,[Work as a member of a cross-functional team t...,Industry\nAutomotive Electrical & Electronic M...,"Oshawa, ON",10000+ employees,Company - Public (GM),Transportation Equipment Manufacturing,$10+ billion (CAD) per year,3.8,62,69,2.8
29,Intellibee Inc,Data Scientist,"Montgomery County, KS",https://www.linkedin.com/jobs/view/2161279589,91400,IBM i2 EIA (MUST) SQL Understanding of Data Wa...,[],Seniority Level\nEntry level\nIndustry\nInform...,"Detroit, MI (US)",Unknown,Company - Public,Unknown,Unknown / Non-Applicable per year,0.0,-1,-1,-1
30,Sanofi,Data Scientist,"Cambridge, MA",https://www.linkedin.com/jobs/view/2007818608,131000,Job Overview:\n\nAdvanced Analytics - Data Sci...,[Get to apply a broad array of capabilities sp...,Seniority Level\nEntry level\nIndustry\nPharma...,Paris (France),10000+ employees,Company - Public (SNY),Biotech & Pharmaceuticals,$10+ billion (CAD) per year,3.8,79,93,2.9
31,Loblaw Digital,Data Scientist,"Toronto, ON",https://www.linkedin.com/jobs/view/1996955933,77250,"At Loblaw Digital, we know that our customers ...","[Build robust, scalable, high performance Pred...",Seniority Level\nEntry level\nIndustry\nInform...,"Toronto, ON",51 to 200 employees,Unknown,Company - Public,Internet,3.1,42,-1,2.7
32,"Aetna, a CVS Health Company",Data Scientist,"New York, NY",https://www.linkedin.com/jobs/view/2161977357,117000,Job Description\n\nLooking for opportunities t...,"[Participates in the development, validation a...",Seniority Level\nEntry level\nIndustry\nInsura...,"Hartford, CT (US)",10000+ employees,1853,Company - Public (AET),Insurance Operators,3.3,61,74,2.7
33,Lockheed Martin,Data Scientist,"Herndon, VA",https://www.linkedin.com/jobs/view/2162842237,112000,Are you ready to take your career to a new lev...,[],Seniority Level\nEntry level\nIndustry\nConstr...,"Bethesda, MD (US)",10000+ employees,Company - Public (LMT),Aerospace & Defence,$10+ billion (CAD) per year,3.9,78,96,2.6
34,Uber,Data Scientist- Rides,"Seattle, WA",https://www.linkedin.com/jobs/view/2023755677,126000,"At Uber, we ignite opportunity by setting the ...",[The Vehicles team owns our vehicle supplier t...,Industry\nComputer Software Consumer Services ...,"San Francisco, CA (US)",10000+ employees,Company - Public (UBER),Computer Hardware & Software,Unknown / Non-Applicable,4.0,80,83,2.9
35,Apple,"Data Scientist, Apple Pay Analytics - Austin","Austin, TX",https://www.linkedin.com/jobs/view/2023687865,111000,"Summary\n\nWe are looking for a hardworking, p...",[],Industry\nConsumer Electronics\nEmployment Typ...,"Cupertino, CA (US)",10000+ employees,Company - Public (AAPL),Computer Hardware & Software,$10+ billion (CAD) per year,4.2,83,93,3
36,Waymo,Data Scientist,"Mountain View, CA",https://www.linkedin.com/jobs/view/2006765491,155000,"At Waymo, we’re focused on bringing self-drivi...",[Safety evaluation is of fundamental importanc...,Seniority Level\nMid-Senior level\nIndustry\nC...,"Mountain View, CA (US)",Unknown,Company - Private,Computer Hardware & Software,Unknown / Non-Applicable,2.9,60,69,2.9
37,Intuit,Data Scientist,"Mountain View, CA",https://www.linkedin.com/jobs/view/2148161834,136000,Overview\n\nWe are looking for a great Data An...,[5+ years of experience in generating and shar...,Seniority Level\nEntry level\nIndustry\nInform...,"Mountain View, CA (US)",5001 to 10000 employees,Company - Public (INTU),Computer Hardware & Software,$2 to $5 billion (CAD) per year,4.3,86,91,3
38,Airtable,Data Scientist,"San Francisco, CA",https://www.linkedin.com/jobs/view/2163898310,144000,Airtable's unique approach to enabling end-use...,"[Partner with product, marketing, and sales te...",Seniority Level\nEntry level\nIndustry\nInform...,"San Francisco, CA (US)",51 to 200 employees,Company - Private,Enterprise Software & Network Solutions,Unknown / Non-Applicable,4.5,82,89,3.3
39,3M,Data Scientist*,"Maplewood, MN",https://www.linkedin.com/jobs/view/2158394845,75200,Job Description:\nData Scientist\n \nCollabora...,[Conduct a variety of data analytics such as: ...,Seniority Level\nEntry level\nIndustry\nInform...,"London, ON",1001 to 5000 employees,Company - Public (MMM),Miscellaneous Manufacturing,$1 to $2 billion (CAD) per year,3.9,79,80,2.8
40,Caterpillar Inc.,Data Scientist,"Peoria, IL",https://www.linkedin.com/jobs/view/2004867934,85900,Description\n\nThe Cat® Digital group is the d...,[ Applying machine learning to time series dat...,Industry\nConstruction Machinery\nEmployment T...,"Deerfield, IL (US)",10000+ employees,Company - Public (CAT),Industrial Manufacturing,$10+ billion (CAD) per year,3.8,74,77,3
41,"Vans, a VF Company",Data Scientist,"Costa Mesa, CA",https://www.linkedin.com/jobs/view/1985230531,91900,Vans: Be a Part of the Original\n\n“It was nev...,"[We are determined. , We are connected to our ...",Seniority Level\nEntry level\nIndustry\nAppare...,"Cypress, CA (US)",5001 to 10000 employees,1966,Subsidiary or Business Segment,General Merchandise & Superstores,4.0,80,91,2.1
42,The Judge Group,Data Scientist,"Woodbridge Township, NJ",https://www.linkedin.com/jobs/view/2007802648,106000,"Location: Woodbridge (Township), NJ\nDescripti...",[ Produces complex predictive models which ena...,Seniority Level\nEntry level\nIndustry\nInform...,"Wayne, PA (US)",1001 to 5000 employees,Company - Private,Staffing & Outsourcing,$100 to $500 million (CAD) per year,3.5,60,76,2.4
43,"IDR, Inc.",Data Scientist,"New York, NY",https://www.linkedin.com/jobs/view/2148117911,123000,Data Scientist\nIDR's largest client is in nee...,"[2+ years of experience in Data Science, 1+ ye...",Seniority Level\nMid-Senior level\nIndustry\nI...,Unknown,Unknown,Unknown,Unknown / Non-Applicable per year,-1,0.0,-1,-1,-1
44,Centers for Disease Control and Prevention,Health Scientist (Data Scientist),"Atlanta, GA",https://www.linkedin.com/jobs/view/2160805881,93400,Duties\nHelp Duties Summary\n\nThe incumbent s...,[Duties<br>\nHelp Duties Summary<br>\n<br>\nTh...,Seniority Level\nAssociate\nIndustry\nResearch...,"Atlanta, GA (US)",10000+ employees,Government,Government Agencies,Unknown / Non-Applicable per year,4.0,84,98,2.8
45,Beyond Limits,Data Scientist,"Glendale, CA",https://www.linkedin.com/jobs/view/2008112009,116000,Description\n\nPosition Overview\n\nOur data s...,"[Ingest, organize, and analyze data from vario...",Seniority Level\nEntry level\nIndustry\nInform...,"Glendale, CA (US)",51 to 200 employees,Company - Private,Research & Development,Unknown / Non-Applicable,4.3,84,-1,2.8
46,Barclays,Data Scientist - Quantexa,"Glasgow, Scotland, United Kingdom",https://www.linkedin.com/jobs/view/2008965009,54737,"Data Scientist\nGlasgow\n\nHere at Barclays, w...",[ Working in conjunction with the wider Financ...,Industry\nBanking Financial Services\nEmployme...,"London, England (UK)",10000+ employees,Company - Public (BARC),Banks & Building Societies,$10+ billion (CAD) per year,3.9,78,83,3.1
47,Bosch USA,Data Scientist,"Sunnyvale, CA",https://www.linkedin.com/jobs/view/1960609409,135000,Job Description\nThis is a technical position ...,[Execute complex data science projects that ha...,,"Gerlingen, Baden-Württemberg (Germany)",10000+ employees,Company - Private,Computer Hardware & Software,$10+ billion (CAD) per year,-1,-1,-1,
48,Xerox,Data Scientist,"Cary, NC",https://www.linkedin.com/jobs/view/1703672073,102000,Xerox (NYSE: XRX) makes every day work better....,[],Seniority Level\nEntry level\nIndustry\nInform...,"Norwalk, CT (US)",10000+ employees,Company - Public (XRX),IT Services,$10+ billion (CAD) per year,3.1,43,54,2.4
49,Purdue University,Data Scientist,"West Lafayette, IN",https://www.linkedin.com/jobs/view/2015626424,57300,Job Summary\n\nThe Data Scientist will conduct...,"[ Master's degree in statistics, research meth...",Seniority Level\nEntry level\nIndustry\nNon-pr...,"West Lafayette, IN (US)",10000+ employees,College / University,Colleges & Universities,$1 to $2 billion (CAD) per year,4.3,88,87,2.4
50,Chewy,Data Scientist,"Dania, FL",https://www.linkedin.com/jobs/view/2011537035,102000,Our Opportunity\n\nChewy's Supply Chain Team i...,[Deep dive big Supply Chain data to explain ch...,Seniority Level\nEntry level\nIndustry\nMarket...,"Dania Beach, FL (US)",10000+ employees,Company - Public (CHWY),Pet & Pet Supply Shops,$2 to $5 billion (CAD) per year,2.9,45,51,2.3
51,Known,Data Scientist,"New York, NY",https://www.linkedin.com/jobs/view/2148257380,127000,About Known\n\nKnown is a modern marketing com...,[ A Masters or PhD from a well-regarded colleg...,Seniority Level\nEntry level\nIndustry\nMarket...,"New York, NY (US)",201 to 500 employees,Company - Private,Advertising & Marketing,$100 to $500 million (CAD) per year,3.5,67,100,4
52,Edrington,Data Scientist,"Glasgow, Scotland, United Kingdom",https://www.linkedin.com/jobs/view/2011661352,54000,Edrington is headquartered in Scotland and emp...,[Lead the consumer data science approach withi...,-1,"Glasgow, Scotland (UK)",1001 to 5000 employees,Company - Private,Food & Drink Manufacturing,$500 million to $1 billion (CAD) per year,3.8,64,95,2.1

In [121]:
jobs.describe(include = 'all')

,company,title,location,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
count,207,207,207,207,207.000000,207,207,207.0,198,198,198,198,198,198,198,198.0,198
unique,180,79,131,207,NaN,203,175,108.0,102,9,71,57,24,27,55,55.0,22
top,CVS Health,Data Scientist,"San Francisco, CA",https://www.linkedin.com/jobs/view/1995091624,NaN,It's a new Day in Healthcare and CVS Health ne...,[],-1.0,"San Francisco, CA (US)",10000+ employees,Company - Private,Computer Hardware & Software,Unknown / Non-Applicable,3.9,100,-1.0,2.8
freq,3,118,14,1,NaN,2,28,15.0,27,72,75,24,48,26,15,28.0,27
mean,NaN,NaN,NaN,NaN,108482.830918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,29549.932068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,11700.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,92141.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,105000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,128000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,205000.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [149]:
common_locations = ['CA', 'NY', 'VA', 'IL', 'WA', 'OR' 'England', 'ON', 'GA', 'MA', 'TX', 'NC', 'MD', 'D.C.', 'NJ', 'MI', 'AZ', 'CO', 'Scotland', 'BC', 'QC', 'Ireland']

def process_location(location):
    location = location.split(",")
    try:
        state_province_country = location[1].strip()
        if state_province_country in common_locations:
            return state_province_country
        else:
            return "Other"
    except:
        return "Other"

In [150]:
jobs['location_bin'] = jobs['location'].apply(process_location)

In [166]:
cols = list(jobs.columns.values)
cols = cols[0:3] + [cols[-1]] + cols[3:17]
jobs = jobs[cols]

In [167]:
jobs

,company,title,location,location_bin,href,salary,description,skills,details,headquarters,company_size,company_type,industry,revenue,company_rating,recommend_to_a_friend,ceo_approval,interview_difficulty
0,TikTok,Data Scientist - TikTok Ads,"Mountain View, CA",CA,https://www.linkedin.com/jobs/view/2148228403,144000,TikTok is the leading destination for short-fo...,[],,-1,-1,-1,-1,-1,-1,-1,-1,2.7
1,Tesla,Data Scientist,"Fremont, CA",CA,https://www.linkedin.com/jobs/view/2147874276,107000,THE ROLE\n\nTesla's mission is to accelerate t...,[ Contribute on all the stages of Data Science...,Seniority Level\nEntry level\nIndustry\nAutomo...,"Palo Alto, CA (US)",10000+ employees,Company - Public (TSLA),Transportation Equipment Manufacturing,$2 to $5 billion (CAD) per year,3.5,59,75,2.9
2,Facebook,"Data Scientist, Finance","Menlo Park, CA",CA,https://www.linkedin.com/jobs/view/2016420647,150000,Facebook's mission is to give people the power...,[Apply your expertise in quantitative analysis...,Industry\nInternet\nEmployment Type\nFull-time...,"Menlo Park, CA (US)",10000+ employees,Company - Public (FB),Internet,$5 to $10 billion (CAD) per year,4.4,90,94,3.1
3,The New York Times,Data Scientist,"New York, NY",NY,https://www.linkedin.com/jobs/view/1988976314,130000,Job Description\n\nThe New York Times is commi...,[ Reframe newsroom and business objectives as ...,Seniority Level\nMid-Senior level\nIndustry\nO...,"New York, NY (US)",1001 to 5000 employees,Company - Public (NYT),News Outlets,$1 to $2 billion (CAD) per year,3.8,80,95,2.9
4,Cerebri AI,Data Scientist,"Toronto, ON",ON,https://www.linkedin.com/jobs/view/1984995996,66225,About Cerebri AI Cerebri AI CVX platform uses ...,[Experience working with and creating data arc...,Seniority Level\nEntry level\nIndustry\nInform...,"Austin, TX (US)",1 to 50 employees,Company - Private,Enterprise Software & Network Solutions,Unknown / Non-Applicable,3.9,75,80,2.4
5,"Anthem, Inc.",Data Scientist,"Atlanta, GA",GA,https://www.linkedin.com/jobs/view/2164180804,102000,Description\n\nSHIFT: Day Job\n\nSCHEDULE: Ful...,"[Statistical Analysis, Scripted Analytics, Pre...",Seniority Level\nEntry level\nIndustry\nInsura...,"Indianapolis, IN (US)",10000+ employees,Company - Public (ANTM),Insurance Operators,$10+ billion (CAD) per year,3.4,63,66,2.7
6,"University of California, San Francisco",Research Data Scientist,"San Francisco, CA",CA,https://www.linkedin.com/jobs/view/1942484976,116000,Job Overview\n\nJob Summary\n\nThe Research Da...,[ BA/BS degree with a major in a related field...,Industry\nHigher Education\nEmployment Type\nF...,"San Francisco, CA (US)",10000+ employees,College / University,Unknown,$50 to $100 million (CAD) per year,4.2,82,89,2.8
7,Loblaw Companies Limited,Data Scientist,"Brampton, ON",ON,https://www.linkedin.com/jobs/view/2148179265,63600,"Location:\n1 Presidents Choice Circle, Brampto...","[Build statistical, descriptive and predictive...",Seniority Level\nEntry level\nIndustry\nInform...,"Brampton, ON",10000+ employees,Company - Public (L),Vehicle Dealers,$10+ billion (CAD) per year,3.5,69,80,2.2
8,The University of British Columbia,Junior Data Scientist,"West Point Grey, BC",BC,https://www.linkedin.com/jobs/view/2008144962,66000,Job Summary\n\nThe UBC Data Science Institute ...,"[ Design, develop, implement and evaluate meth...",Seniority Level\nEntry level\nIndustry\nNon-pr...,"Vancouver, BC",10000+ employees,College / University,Colleges & Universities,$2 to $5 billion (CAD) per year,4.2,87,82,2.7
9,Booz Allen Hamilton,Data Scientist,"Herndon, VA",VA,https://www.linkedin.com/jobs/view/2150469221,85000,Job Number: R0091474\n\nData Scientist\n\nThe ...,"[1+ years of experience with machine learning,...",Seniority Level\nEntry level\nIndustry\nInform...,"McLean, VA (US)",10000+ employees,Company - Public (BAH),Consulting,$5 to $10 billion (CAD) per year,3.9,76,93,2.7
10,PicnicHealth,Data Scientist / Biostatistician,"San Francisco, CA",CA,https://www.linkedin.com/jobs/view/2023894563,144000,Overview\n\nPicnicHealth is all about making m...,"[Use PicnicHealth’s large, multi-disease multi...",,"San Francisco, CA (US)",1 to 50 employees,Company - Private,Computer Hardware & Software,Unknown / Non-Applicable,4.8,100,-1,3
11,Johnson & Johnson,"Principal Data Scientist, Data Sciences","Titusville, NJ",NJ,https://www.linkedin.com/jobs/view/2011683327,125000,"Job Description\n\nJanssen Pharmaceuticals, In...","[Ph.D. with 5 years of industry experience, or...",Industry\nHospital & Health Care Medical Devic...,"New Brunswick, NJ (US)",10000+ employees,Company - Public (JNJ),Biotech & Pharmaceuticals,$10+ billion (CAD) per year,4.1,83,95,2.9
12,Ford Motor Company,Data Scientist,"Dearborn, MI",MI,https://www.linkedin.com/jobs/view/2163903973,97000,Job Description\n\nData Scientist positions of...,[Requires master's or foreign equivalent degre...,Seniority Level\nEntry level\nIndustry\nAutomo...,"Dearborn, MI (US)",10000+ employees,Company - Public (F),Transportation Equipment Manufacturing,$10+ billion (CAD) per year,4.0,80,67,2.8
13,Stripe,"Data Scientist, Radar","Seattle, WA",WA,https://www.linkedin.com/jobs/view/1983860797,157000,We’re looking for data scientists to join the ...,[Work closely with product and business teams ...,-1,"San Francisco, CA (US)",1001 to 5000 employees,Company - Private,Internet,Unknown / Non-Applicable,4.1,83,92,3
14,Amazon Web Services (AWS),Data Scientist,"Seattle, WA",WA,https://www.linkedin.com/jobs/view/1991652913,116000,Description\n\nWhat is the most relevant busin...,"[ Research, develop and build classification a...",Industry\nComputer Software Information Techno...,"Seattle, WA (US)",10000+ employees,Company - Public (AMZN),Internet,$10+ billion (CAD) per year,3.9,77,85,3
15,Square,"Data Scientist, Risk","San Francisco, CA",CA,https://www.linkedin.com/jobs/view/1995037157,153000,Company Description\n\nSquare builds common bu...,"[Diagnose problems and develop compelling, dat...",Seniority Level\nAssociate\nIndustry\nComputer...,"San Francisco, CA (US)",1001 to 5000 employees,Company - Public (SQ),Computer Hardware & Software,$1 to $2 billion (CAD) per year,4.0,81,87,3
16,Bayer,Biotech Data Scientist,"Berkeley, CA",CA,https://www.linkedin.com/jobs/view/1995091624,146000,Your Tasks And Responsibilities\n\nThe primary...,[Work with partners across the Biotech organiz...,Seniority Level\nEntry level\nIndustry\nChemic...,"São Paulo, São Paulo (Brazil)",5001 to 10000 employees,Company - Private,Biotech & Pharmaceuticals,$10+ billion (CAD) per year,4.1,84,72,3
17,Lyft,"Data Scientist, Decisions","New York, NY",NY,https://www.linkedin.com/jobs/view/1991640309,133000,"At Lyft, our mission is to improve people’s li...",[Leverage data and analytic frameworks to iden...,Seniority Level\nMid-Senior level\nIndustry\nI...,"San Francisco, CA (US)",5001 to 10000 employees,Company - Public (LYFT),Computer Hardware & Software,Unknown / Non-Applicable,3.8,68,77,2.8
18,MATCHESFASHION,Data Scientist,"London, England, United Kingdom",England,https://www.linkedin.com/jobs/view/2149281425,57658,At MATCHESFASHION we are on a mission to offer...,[We believe<strong> we all have a part to play...,Seniority Level\nMid-Senior level\nIndustry\nI...,"London, England (UK)",501 to 1000 employees,1987,Company - Private,"Department, Clothing, & Shoe Shops",2.9,44,67,2.5
19,Grammarly,Data Scientist,"San Francisco, CA",CA,https://www.linkedin.com/jobs/view/1995003228,144000,The opportunity\nGrammarly empowers people to ...,"[ Within your first month, you will start deve...",Seniority Level\nEntry level\nIndustry\nInform...,"San Francisco, CA (US)",201 to 500 employees,Company - Private,Internet,Unknown / Non-Applicable,5.0,99,99,2.8
20,JetBlue Airways,Data Scientist,"New York, New York, United States",Other,https://www.linkedin.com/jobs/view/2023647760,120000,Data Scientist\n\nPosition Summary\n\nThe Data...,[Collaborate with teams across the business to...,Seniority Level\nEntry level\nIndustry\nAirlin...,"Long Island City, NY (US)",10000+ employees,Company - Public (JBLU),Transportation Management,$5 to $10 billion (CAD) per year,4.0,78,82,2.8
21,Amazon,Data Scientist,"Seattle, WA",WA,https://www.linkedin.com/jobs/view/2004877102,122000,Description\n\nAre you driven to leverage your...,[ Amazon offers competitive packages including...,Industry\nComputer Software Information Techno...,"Seattle, WA (US)",10000+ employees,Company - Public (AMZN),Internet,$10+ billion (CAD) per year,3.9,77,85,3
22,Tata Group,Data Scientist,"Atlanta, GA",GA,https://www.linkedin.com/jobs/view/2162237772,94700,Researchand develop statistical learning model...,[Researchand develop statistical learning mode...,Seniority Level\nEntry level\nIndustry\nInform...,Mumbai (India),Unknown,Company - Private,Architectural & Engineering Services,$10+ billion (CAD) per year,3.7,78,98,2.9
23,NetApp,Data Scientist,San Francisco Bay Area,Other,https://www.linkedin.com/jobs/view/2004891508,148000,About the Position\nThis Cloud Business Operat...,[Analyze usage and billing data from multiple ...,,"Sunnyvale, CA (US)",10000+ employees,Company - Public (NTAP),Enterprise Software & Network Solutions,$5 to $10 billion (CAD) per year,4.9,87,100,3
24,Statistics Canada,Data Scientist,"Ottawa, ON",ON,https://www.linkedin.com/jobs/view/2004852309,58849,Work Environment:\n\nAre you interested in wor...,[Become familiar with the business case and th...,,"Ottawa, ON",Unknown,Government,Government Agencies,Unknown / Non-Applicable per year,3.8,76,86,2.8
25,Disney Streaming Services,Data Engineer (Marketing Data Eng Team),"New York, NY",NY,https://www.linkedin.com/jobs/view/2163944327,121000,Job Summary\n\nThe Marketing Data Engineering ...,[Build and deploy streaming and batch data pip...,Seniority Level\nMid-Senior level\nIndustry\nI...,"New York, NY (US)",501 to 1000 employees,Company - Private,Internet,Unknown / Non-Applicable,3.7,64,83,2.5
26,Walmart,"Data Scientist, Technology","Bentonville, AR",Other,https://www.linkedin.com/jobs/view/2148159422,91100,Position Summary... What you'll do...\nApplied...,[Applied Business Acumen: Supports the develop...,Seniority Level\nEntry level\nIndustry\nRetail...,"Bentonville, AR (US)",1001 to 5000 employees,Company - Public (WMT),"Department, Clothing, & Shoe Shops",$10+ billion (CAD) per year,3.7,72,87,2.2
27,Kaiser Permanente,Data Scientist,"Oakland, CA",CA,https://www.linkedin.com/jobs/view/2152878571,155000,Description\n\nPerforms advanced data design a...,"[Works with physicians, epidemiologists, stati...",Seniority Level\nEntry level\nIndustry\nFinanc...,"Oakland, CA (US)",10000+ employees,Non-profit Organisation,Healthcare Services & Hospitals,$10+ billion (CAD) per year,4.0,77,81,2.9
28,General Motors,Data Scientist,"Warren, MI",MI,https://www.linkedin.com/jobs/view/2150552482,102000,About GM\n\nThere’s never been a more exciting...,[Work as a member of a cross-functional team t...,Industry\nAutomotive Electrical & Electronic M...,"Oshawa, ON",10000+ employees,Company - Public (GM),Transportation Equipment Manufacturing,$10+ billion (CAD) per year,3.8,62,69,2.8
29,Intellibee Inc,Data Scientist,"Montgomery County, KS",Other,https://www.linkedin.com/jobs/view/2161279589,91400,IBM i2 EIA (MUST) SQL Understanding of Data Wa...,[],Seniority Level\nEntry level\nIndustry\nInform...,"Detroit, MI (US)",Unknown,Company - Public,Unknown,Unknown / Non-Applicable per year,0.0,-1,-1,-1
30,Sanofi,Data Scientist,"Cambridge, MA",MA,https://www.linkedin.com/jobs/view/2007818608,131000,Job Overview:\n\nAdvanced Analytics - Data Sci...,[Get to apply a broad array of capabilities sp...,Seniority Level\nEntry level\nIndustry\nPharma...,Paris (France),10000+ employees,Company - Public (SNY),Biotech & Pharmaceuticals,$10+ billion (CAD) per year,3.8,79,93,2.9
31,Loblaw Digital,Data Scientist,"Toronto, ON",ON,https://www.linkedin.com/jobs/view/1996955933,77250,"At Loblaw Digital, we know that our customers ...","[Build robust, scalable, high performance Pred...",Seniority Level\nEntry level\nIndustry\nInform...,"Toronto, ON",51 to 200 employees,Unknown,Company - Public,Internet,3.1,42,-1,2.7
32,"Aetna, a CVS Health Company",Data Scientist,"New York, NY",NY,https://www.linkedin.com/jobs/view/2161977357,117000,Job Description\n\nLooking for opportunities t...,"[Participates in the development, validation a...",Seniority Level\nEntry level\nIndustry\nInsura...,"Hartford, CT (US)",10000+ employees,1853,Company - Public (AET),Insurance Operators,3.3,61,74,2.7
33,Lockheed Martin,Data Scientist,"Herndon, VA",VA,https://www.linkedin.com/jobs/view/2162842237,112000,Are you ready to take your career to a new lev...,[],Seniority Level\nEntry level\nIndustry\nConstr...,"Bethesda, MD (US)",10000+ employees,Company - Public (LMT),Aerospace & Defence,$10+ billion (CAD) per year,3.9,78,96,2.6
34,Uber,Data Scientist- Rides,"Seattle, WA",WA,https://www.linkedin.com/jobs/view/2023755677,126000,"At Uber, we ignite opportunity by setting the ...",[The Vehicles team owns our vehicle supplier t...,Industry\nComputer Software Consumer Services ...,"San Francisco, CA (US)",10000+ employees,Company - Public (UBER),Computer Hardware & Software,Unknown / Non-Applicable,4.0,80,83,2.9
35,Apple,"Data Scientist, Apple Pay Analytics - Austin","Austin, TX",TX,https://www.linkedin.com/jobs/view/2023687865,111000,"Summary\n\nWe are looking for a hardworking, p...",[],Industry\nConsumer Electronics\nEmployment Typ...,"Cupertino, CA (US)",10000+ employees,Company - Public (AAPL),Computer Hardware & Software,$10+ billion (CAD) per year,4.2,83,93,3
36,Waymo,Data Scientist,"Mountain View, CA",CA,https://www.linkedin.com/jobs/view/2006765491,155000,"At Waymo, we’re focused on bringing self-drivi...",[Safety evaluation is of fundamental importanc...,Seniority Level\nMid-Senior level\nIndustry\nC...,"Mountain View, CA (US)",Unknown,Company - Private,Computer Hardware & Software,Unknown / Non-Applicable,2.9,60,69,2.9
37,Intuit,Data Scientist,"Mountain View, CA",CA,https://www.linkedin.com/jobs/view/2148161834,136000,Overview\n\nWe are looking for a great Data An...,[5+ years of experience in generating and shar...,Seniority Level\nEntry level\nIndustry\nInform...,"Mountain View, CA (US)",5001 to 10000 employees,Company - Public (INTU),Computer Hardware & Software,$2 to $5 billion (CAD) per year,4.3,86,91,3
38,Airtable,Data Scientist,"San Francisco, CA",CA,https://www.linkedin.com/jobs/view/2163898310,144000,Airtable's unique approach to enabling end-use...,"[Partner with product, marketing, and sales te...",Seniority Level\nEntry level\nIndustry\nInform...,"San Francisco, CA (US)",51 to 200 employees,Company - Private,Enterprise Software & Network Solutions,Unknown / Non-Applicable,4.5,82,89,3.3
39,3M,Data Scientist*,"Maplewood, MN",Other,https://www.linkedin.com/jobs/view/2158394845,75200,Job Description:\nData Scientist\n \nCollabora...,[Conduct a variety of data analytics such as: ...,Seniority Level\nEntry level\nIndustry\nInform...,"London, ON",1001 to 5000 employees,Company - Public (MMM),Miscellaneous Manufacturing,$1 to $2 billion (CAD) per year,3.9,79,80,2.8
40,Caterpillar Inc.,Data Scientist,"Peoria, IL",IL,https://www.linkedin.com/jobs/view/2004867934,85900,Description\n\nThe Cat® Digital group is the d...,[ Applying machine learning to time series dat...,Industry\nConstruction Machinery\nEmployment T...,"Deerfield, IL (US)",10000+ employees,Company - Public (CAT),Industrial Manufacturing,$10+ billion (CAD) per year,3.8,74,77,3
41,"Vans, a VF Company",Data Scientist,"Costa Mesa, CA",CA,https://www.linkedin.com/jobs/view/1985230531,91900,Vans: Be a Part of the Original\n\n“It was nev...,"[We are determined. , We are connected to our ...",Seniority Level\nEntry level\nIndustry\nAppare...,"Cypress, CA (US)",5001 to 10000 employees,1966,Subsidiary or Business Segment,General Merchandise & Superstores,4.0,80,91,2.1
42,The Judge Group,Data Scientist,"Woodbridge Township, NJ",NJ,https://www.linkedin.com/jobs/view/2007802648,106000,"Location: Woodbridge (Township), NJ\nDescripti...",[ Produces complex predictive models which ena...,Seniority Level\nEntry level\nIndustry\nInform...,"Wayne, PA (US)",1001 to 5000 employees,Company - Private,Staffing & Outsourcing,$100 to $500 million (CAD) per year,3.5,60,76,2.4
43,"IDR, Inc.",Data Scientist,"New York, NY",NY,https://www.linkedin.com/jobs/view/2148117911,123000,Data Scientist\nIDR's largest client is in nee...,"[2+ years of experience in Data Science, 1+ ye...",Seniority Level\nMid-Senior level\nIndustry\nI...,Unknown,Unknown,Unknown,Unknown / Non-Applicable per year,-1,0.0,-1,-1,-1
44,Centers for Disease Control and Prevention,Health Scientist (Data Scientist),"Atlanta, GA",GA,https://www.linkedin.com/jobs/view/2160805881,93400,Duties\nHelp Duties Summary\n\nThe incumbent s...,[Duties<br>\nHelp Duties Summary<br>\n<br>\nTh...,Seniority Level\nAssociate\nIndustry\nResearch...,"Atlanta, GA (US)",10000+ employees,Government,Government Agencies,Unknown / Non-Applicable per year,4.0,84,98,2.8
45,Beyond Limits,Data Scientist,"Glendale, CA",CA,https://www.linkedin.com/jobs/view/2008112009,116000,Description\n\nPosition Overview\n\nOur data s...,"[Ingest, organize, and analyze data from vario...",Seniority Level\nEntry level\nIndustry\nInform...,"Glendale, CA (US)",51 to 200 employees,Company - Private,Research & Development,Unknown / Non-Applicable,4.3,84,-1,2.8
46,Barclays,Data Scientist - Quantexa,"Glasgow, Scotland, United Kingdom",Scotland,https://www.linkedin.com/jobs/view/2008965009,54737,"Data Scientist\nGlasgow\n\nHere at Barclays, w...",[ Working in conjunction with the wider Financ...,Industry\nBanking Financial Services\nEmployme...,"London, England (UK)",10000+ employees,Company - Public (BARC),Banks & Building Societies,$10+ billion (CAD) per year,3.9,78,83,3.1
47,Bosch USA,Data Scientist,"Sunnyvale, CA",CA,https://www.linkedin.com/jobs/view/1960609409,135000,Job Description\nThis is a technical position ...,[Execute complex data science projects that ha...,,"Gerlingen, Baden-Württemberg (Germany)",10000+ employees,Company - Private,Computer Hardware & Software,$10+ billion (CAD) per year,-1,-1,-1,
48,Xerox,Data Scientist,"Cary, NC",NC,https://www.linkedin.com/jobs/view/1703672073,102000,Xerox (NYSE: XRX) makes every day work better....,[],Seniority Level\nEntry level\nIndustry\nInform...,"Norwalk, CT (US)",10000+ employees,Company - Public (XRX),IT Services,$10+ billion (CAD) per year,3.1,43,54,2.4
49,Purdue University,Data Scientist,"West Lafayette, IN",Other,https://www.linkedin.com/jobs/view/2015626424,57300,Job Summary\n\nThe Data Scientist will conduct...,"[ Master's degree in statistics, research meth...",Seniority Level\nEntry level\nIndustry\nNon-pr...,"West Lafayette, IN (US)",10000+ employees,College / University,Colleges & Universities,$1 to $2 billion (CAD) per year,4.3,88,87,2.4
50,Chewy,Data Scientist,"Dania, FL",Other,https://www.linkedin.com/jobs/view/2011537035,102000,Our Opportunity\n\nChewy's Supply Chain Team i...,[Deep dive big Supply Chain data to explain ch...,Seniority Level\nEntry level\nIndustry\nMarket...,"Dania Beach, FL (US)",10000+ employees,Company - Public (CHWY),Pet & Pet Supply Shops,$2 to $5 billion (CAD) per year,2.9,45,51,2.3
51,Known,Data Scientist,"New York, NY",NY,https://www.linkedin.com/jobs/view/2148257380,127000,About Known\n\nKnown is a modern marketing com...,[ A Masters or PhD from a well-regarded colleg...,Seniority Level\nEntry level\nIndustry\nMarket...,"New York, NY (US)",201 to 500 employees,Company - Private,Advertising & Marketing,$100 to $500 million (CAD) per year,3.5,67,100,4

In [ ]:
jobs[20]['location_bin'] == 'NY'
jobs[23]['location_bin'] == 'CA'
jobs[62]['location_bin'] == 'CA'
jobs[81]['location_bin'] == 'AZ'
jobs[87]['location_bin'] == 'TX'
jobs[88]['location_bin'] == 'BC'
jobs[89]['location_bin'] == 'ON'
jobs[92]['location_bin'] == 'MD'
jobs[94]['location_bin'] == 'England'
jobs[99]['location_bin'] == 'CA'
jobs[109]['location_bin'] == 'CA'
jobs[111]['location_bin'] == 'CA'
jobs[112]['location_bin'] == 'IL'
jobs[120]['location_bin'] == 'ON'
jobs[124]['location_bin'] == 'England'
jobs[125]['location_bin'] == 'NC'
jobs[142]['location_bin'] == 'CA'
jobs[145]['location_bin'] == 'CA'
jobs[146]['location_bin'] == 'QC'
jobs[152]['location_bin'] == 'MA'
jobs[156]['location_bin'] == 'CA'
jobs[178]['location_bin'] == 'MA'
jobs[187]['location_bin'] == 'England'
check if 77 is fixed

In [ ]:
-drop duplicate rows (check)
-enter missing salary data (check)
-identical descriptions?
-identical skills?
-identical details?
-missing values glass door data
-format salary and do conversions (check)
-might not need details column?

In [146]:
x = "San Francisco, CA"
y = x.split(",")
y

['San Francisco', ' CA']

In [ ]:
24 is cad but doesnt show it